import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'text-main': '#0f172a',
                'primary-container': '#2563eb',
                'surface-container': '#ededf9',
                'inverse-surface': '#2e3039',
                'on-primary': '#ffffff',
                'on-primary-container': '#eeefff',
                'on-tertiary-container': '#ffede6',
                'primary-fixed': '#dbe1ff',
                'on-surface-variant': '#434655',
                'success-text': '#047857',
                'outline': '#737686',
                'tertiary-fixed': '#ffdbcd',
                'text-muted': '#6b7280',
                'surface-container-high': '#e7e7f3',
                'on-secondary': '#ffffff',
                'tertiary-fixed-dim': '#ffb596',
                'on-surface': '#191b23',
                'surface-variant': '#e1e2ed',
                'on-secondary-container': '#6f5100',
                'surface': '#faf8ff',
                'secondary-container': '#ffc329',
                'on-secondary-fixed': '#261a00',
                'surface-container-highest': '#e1e2ed',
                'inverse-primary': '#b4c5ff',
                'on-error-container': '#93000a',
                'secondary-fixed': '#ffdf9f',
                'surface-container-low': '#f3f3fe',
                'surface-tint': '#0053db',
                'on-tertiary': '#ffffff',
                'error-container': '#ffdad6',
                'pending-bg': '#fffbeb',
                'surface-bright': '#faf8ff',
                'on-background': '#191b23',
                'tertiary': '#943700',
                'on-error': '#ffffff',
                'success-bg': '#ecfdf5',
                'error': '#ba1a1a',
                'secondary-fixed-dim': '#f9bd22',
                'on-tertiary-fixed-variant': '#7d2d00',
                'on-primary-fixed': '#00174b',
                'inverse-on-surface': '#f0f0fb',
                'pending-text': '#b45309',
                'surface-container-lowest': '#ffffff',
                'outline-variant': '#c3c6d7',
                'background': '#faf8ff',
                'tertiary-container': '#bc4800',
                'secondary': '#795900',
                'on-primary-fixed-variant': '#003ea8',
                'on-tertiary-fixed': '#360f00',
                'bg-base': '#f9fafb',
                'primary': '#004ac6',
                'on-secondary-fixed-variant': '#5c4300',
                'surface-dim': '#d9d9e5',
                'primary-fixed-dim': '#b4c5ff',
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
            spacing: {
                'margin-mobile': '1rem',
                'gutter': '1.5rem',
                'margin-desktop': '2rem',
                'container-max': '80rem',
                'sidebar-width': '16rem',
            },
            fontFamily: {
                'label-bold': ['Inter', ...defaultTheme.fontFamily.sans],
                'display-logo': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'label-sm': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-main': ['Inter', ...defaultTheme.fontFamily.sans],
                'price-display': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-card': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'label-bold': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'display-logo': ['20px', { lineHeight: '28px', letterSpacing: '-0.025em', fontWeight: '800' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'body-main': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'price-display': ['18px', { lineHeight: '28px', fontWeight: '900' }],
                'headline-card': ['16px', { lineHeight: '24px', fontWeight: '700' }],
            },
        },
    },
    plugins: [forms],
};
